---
# This is a sample configmap that helps define a Ceph configuration as required
# by the CSI plugins.

# Sample ceph.conf available at
# https://github.com/ceph/ceph/blob/master/src/sample.ceph.conf Detailed
# documentation is available at
# https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
  namespace: kube-system
data:
  ceph.conf: |
    [global]
    fsid = 9dbd9440-8dfa-4bd9-946f-f8da8ca8a0f1
    public_network = 192.168.10.0/24
    cluster_network = 192.168.10.0/24
    mon_host = 192.168.10.150,192.168.10.151,192.168.10.152
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx

  # keyring is a required key and its value should be empty
  keyring: |

