apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
      version: v1
  template:
    metadata:
      labels:
        app: nginx-demo
        version: v1
    spec:
      containers:
      - name: nginx-demo
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/lib/www/html
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rbd-pvc
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  selector:
    app: nginx-demo
    version: v1
  ports:
  - port: 80
    targetPort: 80
