apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-with-cephfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo-with-cephfs
      version: v1
  template:
    metadata:
      labels:
        app: nginx-demo-with-cephfs
        version: v1
    spec:
      containers:
      - name: nginx-demo-with-cephfs
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/lib/www/html
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nginx-cephfs-pvc-demo
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-with-cephfs
spec:
  selector:
    app: nginx-demo-with-cephfs
    version: v1
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cephfs-pvc-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
